# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  database: <%= ENV.fetch("DB_NAME") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  variables:
    statement_timeout: 60000
  sslmode: require

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", ENV.fetch("DB_NAME")) %>

production:
  url: <%= ENV["DATABASE_URL"] %>
  sslmode: require